import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import Navbar from './component/navbar/Navbar'
//import 'bootstrap/dist/js/bootstrap.bundle.min.js'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Crazy Albums',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
